config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  patch 'flowers/:id' => 'flowers#update'
  get 'flowers/:id/edit' => 'flowers#edit', as:'edit_flower'
  delete 'flowers/:id' => 'flowers#destroy'
  

  resources :flowers do
    resources :likes, only: [:create, :destroy] 
    resources :comments, only: [:create]   
   
  end

  resources :perfumes
  
  get 'flowers/:flower_id/likes' => 'likes#create'
  get 'flowers/:flower_id/likes/:id' => 'likes#destroy'

  root 'flowers#top'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :flower
end

app/models/flower.rb
class Flower < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy

end

app/models/flower_tag_relation.rb
class FlowerTagRelation < ApplicationRecord

end

app/models/flowerword.rb
class Flowerword < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :flower
  belongs_to :user
  validates_uniqueness_of :flower_id, scope: :user_id
end

app/models/perfume.rb
class Perfume < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
     has_many :flowers
     has_many :flowers, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_flowers, through: :likes, source: :flower
  has_many :comments, dependent: :destroy
  
  

  mount_uploader :image, ImageUploader

  def already_liked?(flower)
    self.likes.exists?(flower_id: flower.id)
  end
  
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      flower = Flower.find(params[:flower_id])
      comment = flower.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
     before_action :authenticate_user!

    def index
        @flowers = Flower.all

        if params[:tag_ids]
            @flowers = []
            params[:tag_ids].each do |key, value|      
              
            end
            @flowers.uniq!
          end
    
          if params[:tag]
            Tag.create(name: params[:tag])
          end

    end

    

    def show
        @flower = Flower.find(params[:id])
        @comments = @flower.comments
        @comment = Comment.new
    end

    def new
        @flower = Flower.new
      end

      def edit
        @flower = Flower.find(params[:id])
      end

      def update
        flower = Flower.find(params[:id])
        if flower.update(flower_params)
          redirect_to :action => "show", :id => flower.id
        else
          redirect_to :action => "new"
        end
      end
    
      def create
        flower = Flower.new(flower_params)
        flower.user_id = current_user.id
        if flower.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        flower = Flower.find(params[:id])
        flower.destroy
        redirect_to action: :index
      end
    
    

      private
      def flower_params
        params.require(:flower).permit(:hana, :photo, :image, :overall)
      end 

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


        def create
          like = current_user.likes.create(flower_id: params[:flower_id]) 
          redirect_back(fallback_location: root_path)
        end
      
        def destroy
          like = Like.find_by(flower_id: params[:flower_id], user_id: current_user.id)
          like.destroy
          redirect_back(fallback_location: root_path)
        end
      
      end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
   
        def index
        end
      
        def new
          @perfume = Perfume.new
        end
      
        def show
          @perfume = Perfume.find_by(id: params[:id])
        end
      
        def create
          @perfume = Perfume.new(perfume_params)
          params[:perfume][:question] ? @perfume.question = params[:perfume][:question].join("") : false
          if @perfume.save
              flash[:notice] = "診断が完了しました"
              redirect_to perfume_path(@perfume.id)
          else
              redirect_to :action => "new"
          end
        end
      
      private
        def perfume_params
            params.require(:perfume).permit(:id, question: [])
        end
      end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id]) 
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
      end
     
     
end

app/helpers/flowerwords_helper.rb
module FlowerwordsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flowers/edit.html.erb
<%= form_for @flower do |f| %>
    <%= f.label :hana %>
    <%= f.text_field :hana, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

  <!--アカウント編集時に名前を入力できるようにフォームを追加-->
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <!--アカウント編集時にプロフィールを入力できるようにフォームを追加-->
  <div class="field">
    <%= f.label :profile %><br />
    <%= f.text_area :profile, autofocus: true %>

    <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  </div>

app/views/flowers/index.html.erb
<h1>OKURIBANA</h1>
<h3>一覧ページ</h3>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<%= link_to "新規投稿へ", new_flower_path %>
<div class="flowers-container">
  <% @flowers.each do |t| %>
    <div class="flower">
    <%= t.user.email %>

     <%= link_to "詳細→", flower_path(t.id) %>
     <%= link_to "編集→", edit_flower_path(t.id) %>
     <%= button_to "削除→", flower_path(t.id), method: :delete %>

    <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= button_to flower_like_path(id: t.id, flower_id: t.id), method: :delete do %>
              <p>いいねを取り消し→</p><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= button_to flower_likes_path(id: t.id, flower_id: t.id), method: :post do %>
              <p>いいね</p><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
      <p>いいねの数 = </p><%= t.likes.count %>
  <% end %>

    <%= image_tag t.image_url, size: "250x200" if t.image? %>

    <div>

<h2>総合評価：
<span class="star-rating">
   <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
   <span class="star-rating-back">★★★★★</span>
</span> 
</h2>
</div>

<%= link_to "ログイン", flowers_path %>
<%= link_to "新規登録", new_user_registration_path %>
     
  <% end %>


</div>

app/views/flowers/new.html.erb
</div>
	<div class="cp_contents">
		<h1>OKURIBANA</h1>
		</div>
	</div>
</div>

<h1>写真投稿ページ</h1>
<h3>新規投稿ページ</h3>
<%= form_for @flower do |f| %>


    <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
            <%= tag.label class: 'form-check-label' do %>
                  
                      
                <% end %>

            </div>
        <% end %>
    </div>

    <div class="field">
        <%= f.label :hana  %>
        <%= f.text_area :hana, :size => "30x2" %>
     </div>
  
    <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
    </div>

     <div class="field">
        <%= f.label :photo %>
        <%= f.text_field :photo, :size => 30 %>
     </div>


    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, :size => 30 %>
     </div>
  
   

 
 
  <h5>総合評価</h5>
   <div class="post_form">
    <%= f.radio_button :overall, 5 ,id: 'star1'%>
    <label for="star1"><span class="text">最高</span>★</label>

    <%= f.radio_button :overall, 4 ,id: 'star2'%>
    <label for="star2"><span class="text">良い</span>★</label>

    <%= f.radio_button :overall, 3 ,id: 'star3'%>
    <label for="star3"><span class="text">普通</span>★</label>

    <%= f.radio_button :overall, 2 ,id: 'star4'%>
    <label for="star4"><span class="text">悪い</span>★</label>

    <%= f.radio_button :overall, 1 ,id: 'star5'%>
    <label for="star5"><span class="text">最悪</span>★</label>
 </div>


  <%= f.submit "投稿する" %>
  <% end %>
  
  <%= link_to "一覧に戻る", flowers_path %>


  <div class="cp_cont">
 
  
	<div class="cp_offcm01">
		<input type="checkbox" id="cp_toggle01">
		<label for="cp_toggle01"><span></span></label>
		<div class="cp_menu">
		<ul>
        <li><%= link_to 'HOME🏠', root_path%></li>
		<li><%= link_to 'POST📸', new_flower_path%></li>
		<li><a href="#">menu2</a></li>
		<li><a href="#">menu3</a></li>
		</ul>
		</div>
	

app/views/flowers/show.html.erb
<h1>自分の題名</h1>
<h3>Flower詳細</h3>
<div class="flower">
  <p><%= @flower.hana %></p>
  <p><%= @flower.created_at %></p>
    <% if user_signed_in? %>
      <% if current_user.already_liked?(@flower) %>
        <%= link_to flower_like_path(@flower), method: :delete do %>
          <p>いいねを取り消す</p><%= @flower.likes.count %>
        <% end %>
      <% else %>
        <%= link_to flower_likes_path(@flower), method: :post do %>
          <p>いいね</p><%= @flower.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <p>いいねの数 = </p><%= @flower.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_flower_path(@flower.id) %>
</div>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@flower, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<h2>いいねしたユーザー</h2>
<% @flower.liked_users.each do |user| %>

    <li><%= user.email %></li>

<% end %>

<%= link_to "Flower一覧に戻る", flower_path %>



<%= link_to "編集する", edit_flower_path(@flower.id) %>

<% @flower.tags.each do |tag| %>
    <span><%= tag.name %></span>
<% end %>



<%= image_tag @user.image_url, size: "250x200" if @user.image? %>

app/views/flowers/top.html.erb
<div class="cp_cont">
	<div class="cp_offcm01">
		<input type="checkbox" id="cp_toggle01">
		<label for="cp_toggle01"><span></span></label>
		<div class="cp_menu">
		<ul>
        <li><%= link_to 'POST📸', new_flower_path%></li>
        <li><%= link_to 'HOME🏠', root_path%></li>
        <li><a href="#">menu2</a></li>
		<li><a href="#">menu3</a></li>
		</ul>
		</div>
	</div>
	<div class="cp_contents">
		<h1>OKURIBANA</h1>
		</div>
	</div>
</div>


<div class="cp_modal02">
<input type="checkbox" id="cp_modal" />
<h1>For those of you who send flowers to your loved ones</h1>
<p>大切な人に花を贈る貴方へ</p>
<label for="cp_modal" class="cp_modal_btn"></label>
<label for="cp_modal" class="cp_modal_bg"></label>
<div class="cp_modal_cont">
<label for="cp_modal" class="cp_close"><i class="fa fa-times" aria-hidden="true"></i></label>
	<header>
		<h2>花の社会性</h2>
	</header>
	<article class="cp_content">
		<p>
        花は美しいとか華やかという視覚的な側面だけでなく、
        見る人の心を和らげ、豊かな生活を実感させてくれる側面も持っています。
         花は、人と人、人と社会をつなぐツールとして無限の可能性を秘めており、
         花が人や社会と関わり合うなかで、花と社会との係わり合いの中で、
         花が社会に及ぼすプラスの影響のことを “花の社会性” と呼ぶ。</p>
		<p class=""></p>
	</article>
	<footer><label for="cp_modal" class="cp_btn cp_cl">close</label></footer>
</div>
</div>

<div class="cp_imghover cp_blur">
<%= image_tag "Tinnacriss.jpeg"%>
</div>


</div>

app/views/perfumes/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
    <head><!--ページに表示されない情報(サイトの裏側の設定)-->
        <meta charset="utf-8">
        <title>香水診断スタート</title><!--ブラウザのタブのタイトルを指定-->
    </head>

    <body>
        <header>
            <h1 class="headline">
            <a>Perfu_me</a>
            </h1>
            <ul class="nav-list">
                <li class="nav-list-item">about fragrance</li>
                <li class="nav-list-item"><%= link_to "診断", perfumes_path, class: "link" %></li>
            </ul>
        </header>

        <div class="start">
            <h6>Are you ready?</h6>
            <%= link_to "診断を始める", new_perfume_path, class: "link" %>
        </div>
    </body>

app/views/perfumes/new.html.erb
<%= form_for(@perfume, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="container-sindan">
        <div class="row">
            <div class="col-12">
                <p>Question1. どちらかと言うと…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>じっくり考える方だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>考えるより行動する方だ</p>
            </div>

            <div class="col-12">
                <p>Question2. 自分の価値観として近い方は…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>周りの人と違う存在でありたい</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>周りと同じでいたい</p>
            </div>

            <div class="col-12">
                <p>Question3. 人と接するときは…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>相手の話をよく聞く方だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>自分の話をよくする方だ</p>
            </div>

            <div class="col-12">
                <p>Question4. 大切にしたいのは…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>論理性だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>情緒だ</p>
            </div>
        </div>
    </div>
    <div class="sindanbotan">
        <%= f.submit "post" %>
    </div>
<% end %>

app/views/perfumes/show.html.erb
<div class="intoro">
            <h5>診断結果</h5>
            <p>あなたにおすすめの香りは…</p>
        </div>
        <div class="tweet-container">
            <div class="tweet">

            <% if @perfume.question == "1111" %>
                
                <h6>レモン</h6>
                <p>柑橘系の代表的な原料</p>
                <p>清涼感があり、爽やかな印象</p>

                <% elsif @perfume.question == "1112" %>
                <h6>シトラス</h6>
                <p>オレンジに似た柑橘系の果物</p>
                <p>リラックス効果がある</p>

                <% elsif @perfume.question == "1121" %>
                <h6>ローズ</h6>
                <p>華やかで上品な香り</p>
                <p>ストレスを緩和してくれる効果がある</p>

                <% elsif @perfume.question == "1122" %>
                <h6>ラベンダー</h6>
                <p>優しく女性らしい香り</p>
                <p>気持ちを落ち着かせてくれる</p>

                <% elsif @perfume.question == "1211" %>
                <h6>ジャスミン</h6>
                <p>爽やかなのに官能的な香り</p>
                <p>幸福感を得やすい</p>

                <% elsif @perfume.question == "1212" %>
                <h6>ピーチ</h6>
                <p>フレッシュで優しい香り</p>
                <p>アンチエイジングにも最適</p>

                <% elsif @perfume.question == "1221" %>
                <h6>アップル</h6>
                <p>特徴的で甘い香り</p>
                <p>万人受けしやすい</p>

                <% elsif @perfume.question == "1222" %>
                <h6>ユーカリ</h6>
                <p>しっかりとした優しい香り</p>
                <p>浄化作用があり。気持ちを落ち着かせてくれる</p>

                <% elsif @perfume.question == "2111" %>
                <h6>ローズマリー</h6>
                <p>きりりとした強めの香りが特徴的</p>
                <p>美容効果が高い</p>

                <% elsif @perfume.question == "2112" %>
                <h6>ベルガモット</h6>
                <p>柑橘系の果実</p>
                <p>甘くてフレッシュな、万能な香料</p>

                <% elsif @perfume.question == "2121" %>
                <h6>ムスク</h6>
                <p>雄のジャコウジカの腹部にある香嚢から抽出した香料</p>
                <p>官能的で重い香り</p>

                <% elsif @perfume.question == "2122" %>
                <h6>アンバー</h6>
                <p>マッコウクジラの結石から抽出した香料</p>
                <p>魅惑的で色気のある香り</p>

                <% elsif @perfume.question == "2211" %>
                <h6>シナモン</h6>
                <p>甘いスパイスの香り</p>
                <p>香水のアクセントとしてよく使われる</p>

                <% elsif @perfume.question == "2212" %>
                <h6>バニラ</h6>
                <p>甘くて官能的な香り</p>
                <p>上品で年齢を問わず人気が高い</p>

                <% elsif @perfume.question == "2221" %>
                <h6>イランイラン</h6>
                <p>色気のある濃厚で甘い香り</p>
                <p>恋愛に効果があり</p>

                <% elsif @perfume.question == "2222" %>
                <h6>サンダルウッド</h6>
                <p>お香としてよく使われる白檀の香り</p>
                <p>集中力を高める効果もあり</p>

                <% end %>

        </div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>